name = "performance-hax"
author = "tech"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3e8c74cbb83ff41089087b05d18a1d38efec04ce6a761a241c7372ac23908944"

[versions]
fabric = "0.14.9"
minecraft = "1.19.2"

[options]
acceptable-game-versions = ["1.19.2", "1.19"]
